spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  userDB:
    datasource:
      url: jdbc:postgresql://localhost:5433/userDB
      username: userDB
      password: root
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  contentDB:
    datasource:
      url: jdbc:postgresql://localhost:5434/contentDB
      username: contentDB
      password: root
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


  data:
    redis:
      host: localhost
      port: 6379

cloudinary:
  cloud_name: drpdpl5bt
  api_key: 829315383167681
  api_secret: 9L2OwRv2rMhfjipI8Sbw4x-ndgg

